# Use the official Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project directory into the container
COPY . .

# Set environment variables, if necessary
# ENV FLASK_ENV=production

# Expose the port on which the Flask app will run
EXPOSE 5000

# Define the command to run when the container starts
CMD ["python", "app.py"]

